### ISSUE TITLE
Review the entire document for typos

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#11]
As promised, you may find the SIP specification ready for review at:

https://github.com/DILCISBoard/E-ARK-SIP/blob/master/specification-single-file/E-ARK-SIP_specification-v2.0.0-DRAFT.md

Any typos you find, please commit them directly. Any “hairier” problems, just create issues and assign them to me, please.

**Comment by hsilva-keep** [comment]
I've done my revision & fixes.

**Comment by DrJaime** [comment]
I have also completed my fixes.

Best wishes,


Jaime

**Comment by jmaferreira** [comment]
Work done and published for review.
