### ISSUE TITLE
Support for Shallow IPs

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#110]
Feature request:

Add the possibility of building an SIP (or any other IP for that matter) that is able to move transport the information about the content files, but not the files themselves, i.e. it will only carry pointers to the files.

In theory this is already possible without breaking the current implementation, but it would be nice to add a section to the spec explaining how to accomplish this.

Comment from @karinbredenberg: This information should live on the guidelines and not on the spec (see https://guides.dilcis.eu/guideline/Guideline_IP_and_more_v1_0_0.pdf)

**Comment by jmaferreira** [comment]
According to @karinbredenberg this request violates one of the principles of the CSIP, however there are several use cases where this approach is quite useful.

@shsdev and @luis100 are able to provide some real world use cases.

I would like to bring this discussion to the next DILCIS Board meeting for approval. If this feature is approved, KEEP SOLUTIONS can describe its implementation approach.

**Comment by jmaferreira** [comment]
During the DILCIS board (2022-12-15) it was identified that this approach violates the following CSIP principles:

* Following Principle 3.2, it is strongly recommended that this logical structure is manifested as a physical folder structure.

## Principle 3.2: The Information Package SHOULD ensure that data and metadata are physically separated from one another.

In addition to the logical separation of components, it is beneficial to have data and metadata physically separated (i.e. formatted as individual computer files or clearly separated bitstreams). This allows digital preservation tools and systems to update respective data or metadata portions of an Information Package without endangering the integrity of the whole package.

**Comment by luis100** [comment]
This is a strategy currently being in use by the Portuguese National Archives for the Distributed Digital Preservation service.

When this was presented, there were comments from some E-ARK partners that this strategy could help on large migration projects, specially when we need to wrap files in E-ARK SIP to be able to send them to an E-ARK compatible archive. Requiring files to be within the SIP will temporarily duplicate the amount of storage and requires a lot of I/O which may be unnecessary.

A similar strategy is also used in SIARD to segment SIARD files, for transfer but also for archiving, for example by the Danish National Archives. Although this does not solve the issue completely for SIARD, as a lot of data may not be in LOBS, it may solve the issue for SIPs, as we do not expect much data except for representation data files.

**Comment by shsdev** [comment]
I know about a case where a community member needs to keep large amounts of image data, and they are using S3 to store them. Packaging the data would create a lot of redundancy, therefore they would be interested in having this feature for specific use cases.

**Comment by karinbredenberg** [comment]
The agenda for the next meeting is already filled it needs to be on the one after that, @jmaferreira

**Comment by karinbredenberg** [comment]
Following the decision at the DILCIS Board meeting on the 6th of February a working group is created.
See: [https://github.com/DILCISBoard/GroupDocumentation/blob/master/MeetingNotes/2024/20240206%20DILCIS%20Board%20and%20EARK%20CSP%20CORE11%20and%20others.md](https://github.com/DILCISBoard/GroupDocumentation/blob/master/MeetingNotes/2024/20240206%20DILCIS%20Board%20and%20EARK%20CSP%20CORE11%20and%20others.md)

**Comment by jmaferreira** [comment]
**ISSUE MOVED TO CSIP**

This issue has been moved to the Common Specification (CSIP) project as the feature requested has impact on all information packages (SIP, AIP and DIP).

Please refer to https://github.com/DILCISBoard/E-ARK-CSIP/issues/747 for additional information and comments.
