### ISSUE TITLE
Verify the cardinality of `metsHdr/agent/name`

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#117]
In the following example:
https://github.com/DILCISBoard/E-ARK-SIP/blob/master/profile/E-ARK-SIP.xml#L225

the cardinality should be `1..1` and not `0..1`.

**Comment by karinbredenberg** [comment]
Observe that no new release have been made so the changes are in a staging branch.

**Comment by jmaferreira** [comment]
You're absolutly right. Sorry for confusion.
