### ISSUE TITLE
SIP19 Submitting Agenbt Additional Information

### ISSUE THREAD

**Issue by stephenmackey** [DILCISBoard/E-ARK-SIP#126]
SIP 19 has the text: 'The submitting agent has a note providing a unique identification code
for the archival creator.'

This should be: 'The submitting agent has a note providing a unique identification code
for the archival **submitter.'** or if free text is to be allowed 'The submitting agent has a note providing information about the submitter, e.g. contact details.'

**Comment by jmaferreira** [comment]
Thanks for catching that.
This has been fixed on commit d9ea46a2a377830f4ea6fcdbd11f125b6c52c5f8
