### ISSUE TITLE
The are nulls in the auto-generated markdown

### ISSUE THREAD

**Issue by hsilva-keep** [DILCISBoard/E-ARK-SIP#18]
In the profile, content like (**I think the problem is the last paragraph, because it has an anchor**)
```xml
<requirement ID="SIP5" REQLEVEL="MAY" RELATEDMAT="VocabularyaltrecordIDTYPE" EXAMPLES="metsHdrElementExample1">
  <description>
    <head>Submission agreement</head>
    <p xmlns="http://www.w3.org/1999/xhtml">A reference to the Submission Agreement associated with the package.</p>
    <p xmlns="http://www.w3.org/1999/xhtml">@TYPE is used with the value "SUBMISSIONAGREEMENT".</p>
    <p xmlns="http://www.w3.org/1999/xhtml">Example: RA 13-2011/5329; 2012-04-12</p>
    <p xmlns="http://www.w3.org/1999/xhtml">Example: http://submissionagreement.kb.se/dnr331-1144-2011/20120711/</p>
    <p xmlns="http://www.w3.org/1999/xhtml">Note: It is recommended to use a machine-readable format for a better description of a submission agreement.</p>
    <p xmlns="http://www.w3.org/1999/xhtml">For example, the submission agreement developed by Docuteam GmbH <a href="http://www.loc.gov/standards/mets/profiles/00000041.xml">http://www.loc.gov/standards/mets/profiles/00000041.xml</a>
  </p>
  <dl xmlns="http://www.w3.org/1999/xhtml">
    <dt>METS XPath</dt>
    <dd>metsHDR/altrecordID</dd>
    <dt>Cardinality</dt>
    <dd>0..1</dd>
  </dl>
</description>
</requirement>
```
generates a null.

Also, if the controlled vocabulary is not present, a null is also generated. Example:
```xml
<requirement ID="SIP4" REQLEVEL="MUST" RELATEDMAT="VocabularyOAISPackageType" EXAMPLES="metsHdrElementExample1">
  <description>
    <head>OAIS Package type information</head>
    <p xmlns="http://www.w3.org/1999/xhtml">@csip:OAISPACKAGETYPE is used with the value "SIP".</p>
    <dl xmlns="http://www.w3.org/1999/xhtml">
      <dt>METS XPath</dt>
      <dd>metsHdr/@csip:OAISPACKAGETYPE</dd>
      <dt>Cardinality</dt>
      <dd>1..1</dd>
    </dl>
  </description>
</requirement>
```

**Comment by jmaferreira** [comment]
Added @karinbredenberg to the mix. I think she should be aware of this.

**Comment by carlwilson** [comment]
@hsilva-keep I can see the problem with `SIP4`. It's to do with the related matter ID `VocabularyOAISPackageType` that should point to a vocabulary definition in the profile but doesn't (hence the null). There's two choices, add the element to the vocabs list and / or add a catch to the code to ignore missing lookups completely.

**Comment by hsilva-keep** [comment]
@carlwilson both solutions can exists. I mean, the obvious solution for it is to add the missing vocabulary definition (not quite sure if a METS profile can "inherit" from another @karinbredenberg) but a gracious way to deal with it is also appreciated. Something like stating that the vocabulary is not defined in the profile.

**Comment by carlwilson** [comment]
@hsilva-keep I think that there's an issue as it's probably (certainly) wrong to refer to an id outside of the current document.

**Comment by hsilva-keep** [comment]
@carlwilson Yes, indeed, we're talking about XML and not XML Schemas (that could extend each other).

**Comment by carlwilson** [comment]
Fix added to the profile generator for null lookups, still looking at the link in text issue.

**Comment by jmaferreira** [comment]
@carlwilson Can we close this issue?

**Comment by jmaferreira** [comment]
Ping!

**Comment by karinbredenberg** [comment]
I'll add the vocabulary reference.
