### ISSUE TITLE
Tables: "See also” in the end of some cells is not clear, for example where does "See also: Alternative records ID's” actually refer to?

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#20]

**Comment by jmaferreira** [comment]
The problem here, is that the See also text refers to something that is nowhere to be found on the text or table i.e. "Alternative record ID’s". We should use the exact text found on the "Name & Location" column of the table to better guide the user.

@karinbredenberg Do you agree?

**Comment by karinbredenberg** [comment]
WE need to have it the same in all the specs so hold on for a while.

**Comment by jmaferreira** [comment]
@karinbredenberg Any progress on this issue?

**Comment by karinbredenberg** [comment]
No not yet.

**Comment by jmaferreira** [comment]
@karinbredenberg Any progress on this issue?

**Comment by karinbredenberg** [comment]
The see also comes from the related material attribute. In the CSIP its most often to vocabularies so it gives a link to the vocabulary used.
The title in this case points to another requirement? Some additions into the transformation might be needed so it points and goes to the requirement instead.

**Comment by carlwilson** [comment]
Fixed in v2.0.1

**Comment by karinbredenberg** [comment]
The transfomration has been updated so the See also points to the correct place.
