### ISSUE TITLE
Example in Page 17: CSIP agent requirement (software agent) is missing.

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#21]

**Comment by jmaferreira** [comment]
The SIP spec does not bring any special requirements regarding software agents. It inherits these requirements from the CS IP.

@karinbredenberg Since this is a mandatory element in the CS IP, should it also be in the examples given at the SIP level? Which approach have you been following while writing the profiles?

**Comment by karinbredenberg** [comment]
The SIP profile only contains the things different from CSIP.  But yes we can add the examples from the CSIP if needed.

**Comment by jmaferreira** [comment]
@karinbredenberg Are you going to enhance the examples already written in the METS profile to address this issue?

**Comment by karinbredenberg** [comment]
The full example is provided in the appendix. Isn't that enough? Does it really need to be also the small example chunks? We should next to the table just have the examples close to the text that describes what the table is about.

**Comment by jmaferreira** [comment]
I agree. Wont fix then.
