### ISSUE TITLE
SIP32: "Follows the requirements in the CSIP profile", but CSIP does not say anything about this. Is this E-ARK specific attribute actually needed, since there is @MIMETYPE?

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#24]

**Comment by jmaferreira** [comment]
The element optional `fileSec/fileGrp/file/@sip:FILEFORMATNAME` may be used by the implementer if the MIMETYPE is not sufficient for the purposes of processing/ingesting the information package.

**Comment by karinbredenberg** [comment]
Needs to be checked in the profile and transformation of the profile to md.

**Comment by karinbredenberg** [comment]
Ok, these comes from the dmdSec, amdSec and structMap parts of the profile which currently don't have a requirement number just stating that they are following the CSIP.

**Comment by jmaferreira** [comment]
I've implemented by own suggestion on requirement SIP32:

> An optional attribute may be used if the MIMETYPE is not sufficient for the purposes of processing the information package.

**Comment by jmaferreira** [comment]
@carlwilson Hi Carl. While generating the markdown tables from the SIP profiles there are a couple of sentences that are placed within SIP32 (for example) that shouldn't be there.

The generated MD is:

| ID | Name & Location | Description & usage | Cardinality & Level |
| --- | --------------- | ------------------- | ------------------- |
| <a name="SIP32"></a>**SIP32** | **File format name** <br/> `fileSec/fileGrp/file/@sip:FILEFORMATNAME` | Follows the requirements in the CSIP profile. <br/> Follows the requirements in the CSIP profile. <br/> An optional attribute may be used if the MIMETYPE is not sufficient for the purposes of processing the information package. <br/> Example: "Extensible Markup Language” <br/> Example: ”PDF/A” <br/> Example: ”ISO/IEC 26300:2006” | **0..1** <br/> MAY |
| <a name="SIP33"></a>**SIP33** | **File format version** <br/> `fileSec/fileGrp/file/@sip:FILEFORMATVERSION` | The version of the file format when the use of PREMIS has not been agreed upon in the submission agreement. <br/> Example: "1.0” | **0..1** <br/> MAY |
| <a name="SIP34"></a>**SIP34** | **File format registry** <br/> `fileSec/fileGrp/file/@sip:FILEFORMATREGISTRY` | The name of the format registry used to identify the file format when the use of PREMIS has not been agreed upon in the submission agreement. <br/> Example: "PRONOM” | **0..1** <br/> MAY |
| <a name="SIP35"></a>**SIP35** | **File format registry key** <br/> `fileSec/fileGrp/file/@sip:FILEFORMATKEY` | Key of the file format in the registry when use of PREMIS has not been agreed upon in the submission agreement. <br/> Example: "fmt/101” | **0..1** <br/> MAY |

**Comment by carlwilson** [comment]
Hi @jmaferreira is there a reason that the requirements don't have an ID. I can fix the code (two tweaks) but am curious about the reason, and the correct output.

**Comment by karinbredenberg** [comment]
A reference id has been made so the section is created with the correct statements and can be included in the specification.
