### ISSUE TITLE
What is the difference between SIP12 and SIP9 on page 32-33. A bit confusing with what is meant by creator. Is it the creator of the SIP or the creator of the original information? Please clearify

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#28]

**Comment by jmaferreira** [comment]
@karinbredenberg I believe this one is for you. We need to clarify on the profiles what is the difference between requirement SIP 9 and SIP 12. They hold the exact same description as we stand now:


> The name of the organisation or person that originally created the data being transferred. <br/> Please note that this might be different from the organisation which has been charged with preparing and sending the SIP to the archives.

I suggest updating the description of SIP to be somewhat in the lines of:

> A wrapper element that enables to encode the name of the organisation or person that originally created the data being transferred. <br/> Please note that this might be different from the organisation which has been charged with preparing and sending the SIP to the archives.

**Comment by jmaferreira** [comment]
I've already changed the profile with my suggestion. If you disagree, please change directly on the profile and generate documentation again.

**Comment by karinbredenberg** [comment]
Just removed the text duplication.

**Comment by jmaferreira** [comment]
Fixed.
