### ISSUE TITLE
General: All extra elements for SIP, AIP and DIP should be included in CSIP

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#30]
In [our country] we have not created separate FGSs for SIP, AIP and DIP. 

We recommend that all extra elements for SIP, AIP and DIP should be included in CSIP, but as optional information. Then, documents are needed that describe how to create a SIP, AIP, DIP and how to use the elements at EU level and that it is possible to adapt for local use in different countries.

**Comment by jmaferreira** [comment]
To be discussed in front of the whole DILCIS Board.

**Comment by karinbredenberg** [comment]
Connected to issue https://github.com/DILCISBoard/E-ARK-CSIP/issues/371

**Comment by jmaferreira** [comment]
@karinbredenberg Has there been any decision on this topic? I need a strategic decision in order to implement at the SIP level.

**Comment by karinbredenberg** [comment]
I'll put it up on the agenda for Wednesday.

**Comment by karinbredenberg** [comment]
From todays meeting:
Seeing the complexity having it all in one document the suggestion is to not do a combined document. There will be things raised from SIP/AIP/DIP to the CSIP.

**Comment by jmaferreira** [comment]
Thanks Karin. Will close the issue then.
