### ISSUE TITLE
The documents for the different IPs should be standardized

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#31]
The documents for the different IPs should be standardized so that they are structured in a similar way and the references should keep the same ID for the same element (CSIP7 should always be the same element in all documents).

**Comment by jmaferreira** [comment]
This is two issues in one:

- [ ] The documents for the different IPs should be standardized so that they are structured in a similar way 
- [ ] References should keep the same ID for the same element (CSIP7 should always be the same element in all documents).

**Comment by jmaferreira** [comment]
Points of standardisation between specs:

- [ ] List of authors and reviewers (at least the way this information is presented)
- [ ] History of the specification
- [ ] Spec map or guide through the entire set of specifications
- [ ] Overall design including cover and images
- [ ] Section names and order

**Comment by karinbredenberg** [comment]
Connected to issue: https://github.com/DILCISBoard/E-ARK-CSIP/issues/372

**Comment by jmaferreira** [comment]
The issue "References should keep the same ID for the same element (CSIP7 should always be the same element in all documents)." has been decided not to be implemented. See https://github.com/DILCISBoard/E-ARK-CSIP/issues/372 for more information.

**Comment by jmaferreira** [comment]
@karinbredenberg I'm waiting for instructions regarding the way IPs should be standardized so that they are structured in a similar way. Is there one IP initiative that will serve as a inspiration to others?

**Comment by jmaferreira** [comment]
@DrJaime Hi Jaime, I guess you are making the new images for the specs. Do we have new images for the SIP already? Where can I find them?

**Comment by karinbredenberg** [comment]
Its on its way.

**Comment by jmaferreira** [comment]
Images attached.

[SIP.zip](https://github.com/DILCISBoard/E-ARK-SIP/files/3172869/SIP.zip)

**Comment by jmaferreira** [comment]
Hi @karinbredenberg and @PhillipTommerholt ,

I guess we are not doing the alignment of "Section names and order" between all the specs.
I'm closing this for now.
