### ISSUE TITLE
Chapter 3.4

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-SIP#38]
Comment left  in a mail to info@dilcis.eu

3.4 states that “Although seldom used, preservation metadata can be included in an SIP”. I understand that this captures technical metadata (file format etc.) but I’m wondering if it includes also actions/events on the SIP. Is it suggested to create a PREMIS event to mark the creation of the METS SIP or the metsHdr information is considered sufficient for this purpose? If the latter is true, then I’m wondering to what kind of PREMIS event does the example under 5.2 (Example 4: Example of a whole METS document describing an submission information package with no representations) refers to?

**Comment by jmaferreira** [comment]
I've added the following text:

The METS administrative metadata section `<amdSec>` is used to include or reference technical and preservation metadata.

Although seldom used, preservation metadata can be included in an SIP. The guide on [Using PREMIS with METS](https://www.loc.gov/standards/premis/premis-mets.html) provides recommendations on how to use the `<amdSec>` element to reference PREMIS metadata. Preservation metadata is typically used to record the history of preservation events that influence the state of the information package. Normally, these take place after the package has been ingested into a digital repository, however an example of preservation event that can occur prior to the ingest process is the digitization of analogue material. This event takes place before the information is ingested and can be included in an SIP.

@karinbredenberg Do you agree with this?

**Comment by karinbredenberg** [comment]
@jmaferreira I do.

**Comment by jmaferreira** [comment]
Done.
