### ISSUE TITLE
NOTETYPE's value not reflected in METS Extensions

### ISSUE THREAD

**Issue by elbre** [DILCISBoard/E-ARK-SIP#68]
Good day,
SIP specification is enlarging attribute "NOTETYPE" of value "IDENTIFICATIONCODE". But this value is mentioned only in the External Vocabularies but not in the METS Extensions itself (neither CSIP or SIP. 
I rather not specify in which it should be placed since you told me in the past that "notetype" belongs to the csip with a prefix.

**Comment by jmaferreira** [comment]
@karinbredenberg Do you care to comment?

**Comment by karinbredenberg** [comment]
WE are working on updating this.

**Comment by karinbredenberg** [comment]
Thanks for catching this @elbre ! It has been updated with PR #71 .
