### ISSUE TITLE
Update in image due to name change of CITS Geodata

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/E-ARK-SIP#74]
CITS Geodata is renamed to Geospatial data. Update is needed in the image.

[https://github.com/DILCISBoard/E-ARK-SIP/blob/master/specification/images/Fig_1_SIP.svg](https://github.com/DILCISBoard/E-ARK-SIP/blob/master/specification/images/Fig_1_SIP.svg)

**Comment by karinbredenberg** [comment]
This image is obsolete since its to old preface image.

**Comment by jmaferreira** [comment]
@DrJaime Can you produce a new image?

**Comment by karinbredenberg** [comment]
A new images is made and is in the preface part of the spec-publisher. Solved with PR in https://github.com/DILCISBoard/spec-publisher

**Comment by karinbredenberg** [comment]
This issue can be closed.
