### ISSUE TITLE
Quotations are not being transported to the HTML rendered version of the markdown version of the spec. On the PDF is fine.

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#92]
The quotation markup is not being transported to the output renders of the spec. Can we fix this?

Output:
<img width="1792" alt="Screenshot 2020-06-17 at 10 18 20" src="https://user-images.githubusercontent.com/3181302/84880070-fbcde300-b083-11ea-8227-075e34143839.png">

Source:

<img width="1584" alt="Screenshot 2020-06-17 at 10 17 15" src="https://user-images.githubusercontent.com/3181302/84880119-09836880-b084-11ea-83db-b8a6e4b60612.png">

PDF Version:

<img width="968" alt="Screenshot 2022-05-03 at 08 18 56" src="https://user-images.githubusercontent.com/3181302/166416853-a4d6d503-ab55-4b70-87c0-9b551dc2822d.png">

**Comment by jmaferreira** [comment]
This is a rendering issue. It only affects the  HTML  version. Moving this to the Website milestone.

**Comment by jmaferreira** [comment]
@carlwilson The new rendering process still does not carry the highlighted text to the HTML version. Should we dismiss this issue or is it worth addressing it?

**Comment by carlwilson** [comment]
I'll take a look @jmaferreira , there's no time like the present and all that. I have another issue I'd like to address also.

**Comment by carlwilson** [comment]
Fixed by DILCISBoard/spec-publisher#38. Results at <http://sip.openpreservation.org/>. Close if OK please.
