### ISSUE TITLE
"REF_CSIP_1" - Is this how it should look?

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#94]
Hi Karin,

<img width="1792" alt="Screenshot 2020-06-17 at 10 26 10" src="https://user-images.githubusercontent.com/3181302/84881045-3f751c80-b085-11ea-90fc-a5aac8ac3acb.png">

Is this a feature or a bug? I don't recall seeing this reference notation anywhere else in the specs.

**Comment by karinbredenberg** [comment]
Its the ID's of the sections in the profile that are not described in the SIP but the section is there in the profile to make sure all knows its the CSIP only used for that section. So its a feature.

**Comment by jmaferreira** [comment]
Ok
