### ISSUE TITLE
Do we have transparent version of the logos that we can use?

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#95]
<img width="1792" alt="Screenshot 2020-06-17 at 10 28 53" src="https://user-images.githubusercontent.com/3181302/84881188-6af80700-b085-11ea-8d3c-2bc579173fa5.png">

In my screen is very noticeable.

It would also be nice to publish vector/SVG versions of the logos on the DILCIS website.

**Comment by karinbredenberg** [comment]
For DILCIS yes, for DLM no.

**Comment by jmaferreira** [comment]
I found a transparent version online. Not very big though!

![dlm-logo](https://github.com/DILCISBoard/E-ARK-SIP/assets/3181302/eff13351-94e0-4e85-948f-41c581dc9400)

**Comment by karinbredenberg** [comment]
Observe that the logos we have been given acces to i s placed here, [https://github.com/DILCISBoard/spec-publisher/tree/master/site/img](https://github.com/DILCISBoard/spec-publisher/tree/master/site/img)
